export const AssessmentConstants = {
    GET_PATIENTS_REQUEST: 'ASSESS_GET_PATIENTS_REQUEST',
    GET_PATIENTS_SUCCESS: 'ASSESS_GET_PATIENTS_SUCCESS',
    GET_PATIENTS_FAILURE: 'ASSESS_GET_PATIENTS_FAILURE',
};
