export const ResponseConstants = {
  GET_LIST_REQUEST: 'RESPONSE_GET_LIST_REQUEST',
  GET_LIST_SUCCESS: 'RESPONSE_GET_LIST_SUCCESS',
  GET_LIST_FAILURE: 'RESPONSE_GET_LIST_FAILURE', 

  ADD_ANSWER_REQUEST: 'RESPONSE_ADD_ANSWER_REQUEST',
  ADD_ANSWER_SUCCESS: 'RESPONSE_ADD_ANSWER_SUCCESS',
  ADD_ANSWER_FAILURE: 'RESPONSE_ADD_ANSWER_FAILURE',

};
