export const ResponseConstants = {
  GET_LIST_REQUEST: 'RESPONSE_GET_LIST_REQUEST',
  GET_LIST_SUCCESS: 'RESPONSE_GET_LIST_SUCCESS',
  GET_LIST_FAILURE: 'RESPONSE_GET_LIST_FAILURE', 

  ADD_ANSWER_REQUEST: 'RESPONSE_ADD_ANSWER_REQUEST',
  ADD_ANSWER_SUCCESS: 'RESPONSE_ADD_ANSWER_SUCCESS',
  ADD_ANSWER_FAILURE: 'RESPONSE_ADD_ANSWER_FAILURE',

  ADD_REQUEST: 'RESPONSE_ADD_REQUEST',
  ADD_SUCCESS: 'RESPONSE_ADD_SUCCESS',
  ADD_FAILURE: 'RESPONSE_ADD_FAILURE',

  SET_PROCEDURE_REQUEST: 'RESPONSE_SET_PROCEDURE_REQUEST',
  SET_PROCEDURE_SUCCESS: 'RESPONSE_SET_PROCEDURE_SUCCESS',
  SET_PROCEDURE_FAILURE: 'RESPONSE_SET_PROCEDURE_FAILURE',
}
