export const StudyConstants = {
    GET_PATIENTS_REQUEST: 'STUDY_GET_PATIENTS_REQUEST',
    GET_PATIENTS_SUCCESS: 'STUDY_GET_PATIENTS_SUCCESS',
    GET_PATIENTS_FAILURE: 'STUDY_GET_PATIENTS_FAILURE',
};
