export const StudyConstants = {
    GET_PATIENT_LIST_REQUEST: 'STUDY_GET_PATIENT_LIST_REQUEST',
    GET_PATIENT_LIST_SUCCESS: 'STUDY_GET_PATIENT_LIST_SUCCESS',
    GET_PATIENT_LIST_FAILURE: 'STUDY_GET_PATIENT_LIST_FAILURE',

    INIT_REQUEST: 'STUDY_INIT_REQUEST',
    INIT_SUCCESS: 'STUDY_INIT_SUCCESS',
    INIT_FAILURE: 'STUDY_INIT_FAILURE',

    FOCUS_ITEMS_REQUEST: 'STUDY_FOCUS_ITEMS_REQUEST',
    FOCUS_ITEMS_SUCCESS: 'STUDY_FOCUS_ITEMS_SUCCESS',
    FOCUS_ITEMS_FAILURE: 'STUDY_FOCUS_ITEMS_FAILURE',
};
