export const StudyConstants = {
    GET_PATIENT_LIST_REQUEST: 'STUDY_GET_PATIENT_LIST_REQUEST',
    GET_PATIENT_LIST_SUCCESS: 'STUDY_GET_PATIENT_LIST_SUCCESS',
    GET_PATIENT_LIST_FAILURE: 'STUDY_GET_PATIENT_LIST_FAILURE',
};
